// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlzslhupbwzqjpupeibx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsenNsaHVwYnd6cWpwdXBlaWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjY3NzMsImV4cCI6MjA3NjgwMjc3M30.FRL5co53aEr2qTCqREuuSr2DC2IODOxyflzJf3krdM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});